### ISSUE TITLE
Obrazovka načítání nezobrazuje české znaky

### ISSUE THREAD

**Issue by kudlav** [kmzbrnoI/hJOPpanel#34]
Panely verze 1.12.3 a 1.12.2 nezobrazují diakritiku během načítání u následujících stavů:
- Načítám symboly "symbols" ...
- Načítám symboly "text" ...

A patrně i další uložené v Symbols.pas.
Ostatní řetězce ("Vytvářím panel...") se zobrazují korektně.

https://github.com/kmzbrnoI/hJOPpanel/blob/6c5524305a57346df950694336b40ca62cb9c1d4/src/panel/Symbols.pas#L155-L161

**Comment by horacekj** [comment]
Jo, tohle je vtipná chyba. A oobčas je nějaký diakriita rozbitá. Vůbec nevím, proč se to děje :/
